In [118]:
#SCRIPT PARA ABRIR IMAGEN CON SCIKIT
#https://scikit-image.org/docs/stable/api/skimage.io.html#skimage.io.plugin_info
from skimage import data, io
from skimage.color import rgb2grey
import numpy as np
import pandas as pd

img = io.imread('.\\Imagenes\\lena_color_512.tif')
gray_img = rgb2grey(img)
io.imshow(gray_img)
print(gray_img)
print(gray_img.shape)


[[0.60802863 0.60802863 0.60779059 ... 0.64137412 0.57998235 0.46985725]
 [0.60802863 0.60802863 0.60779059 ... 0.64137412 0.57998235 0.46985725]
 [0.60802863 0.60802863 0.60779059 ... 0.64137412 0.57998235 0.46985725]
 ...
 [0.13746353 0.13746353 0.16881412 ... 0.37271804 0.35559529 0.34377725]
 [0.14617059 0.14617059 0.18730588 ... 0.36788784 0.37292549 0.38467529]
 [0.14617059 0.14617059 0.18730588 ... 0.36788784 0.37292549 0.38467529]]
(512, 512)


In [119]:
newArray = np.array([])
#imgPlana = gray_img.flatten()
#print('Tamaño: ', imgPlana.shape)
#print(imgPlana)

#Dividimos la primer column en subarrays de 4 elementos. Cada pixel tiene 1 componente al ser escala de grises
arraySegmentado = np.split(gray_img[:,0], 256) #Segmenta la fila en 128 arreglos (4 elementos cada subarreglos)
print('No. de arrays de 4 elementos: ', len(arraySegmentado))
#print(arraySegmentado)


for j in range(len(arraySegmentado)): #Filas
    for i in range(len(arraySegmentado)): # Elementos de filas
        promedio = arraySegmentado[i].mean()
        newArray = np.append(promedio, newArray)
            

arrayFinal = np.reshape(newArray, (256,256))
#print(newArray)
print('Tamaño: ', arrayFinal.shape)
#print(newArray)


No. de arrays de 4 elementos:  256
Tamaño:  (256, 256)


In [120]:
#Ahora vamos a mostrar la imagen 
import matplotlib.pyplot as plt
plt.rcParams['image.cmap'] = 'gray'
%matplotlib inline

plt.imshow(arrayFinal,vmin=0,vmax=1)